config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:new, :create]

  root 'pages#home'

  get '/about', to: 'pages#about'
  get '/blog', to: 'pages#blog'
  get '/contact', to: 'contacts#new'
  get '/gallery', to: 'pages#gallery'
  get '/message_input', to: 'pages#message_input'
  get '/address_input', to: 'pages#address_input'
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,      :validate => true
  	attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  	attribute :message,   :validate => true	
  	attribute :nickname,  :captcha  => true

  	# Declare the e-mail headers. It accepts anything the mail method
  	# in ActionMailer accepts.
  	def headers
  		{
  			:subject => "Contact Form",
      		:to => "hello@grafficards.com",
      		:from => %("#{name}" <#{email}>)
    	}
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = "Cannot send message"
			render new
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def about
	end

	def contact
	end

	def blog
	end

	def gallery
	end

	def message_input 
	end

	def address_input
	end

	def payment
	end

	def card_sent
	end

	def page_not_found
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<div class='container center contact_message_sent'>
<h4 class="header col s12 light">Thank you for your message!</h4>
	<p>We'll get back to you soon.</p>
	<%= image_tag "9.png", :width =>"250" %>
</div>

app/views/contacts/new.html.erb
<br><br>
<div class="row center">
	<h4 class="header col s12 light">Contact us</h4>
</div>

	<%= form_for @contact do |f| %>
	<div class='contact_container input-field'>
		<%= f.label :name %> <br>
		<%= f.text_field :name, required: true %><br><br>
	</div>
	<div class='contact_container input-field validate'>
		<%= f.label :email %> <br>
		<%= f.email_field :email, required: true %><br><br>
		</div>
		<div class='contact_container input-field'>
		<%= f.label :message %> <br>
		<%= f.text_area :message, as: :text %>
	</div>
	<div class="hidden">
		<%= f.label :nickname %> <br>
		<%= f.text_field :nickname, hint: 'leave this field blank' %>
	</div>
	<br><br>

	<div class="row center next_button">
	<%= f.submit 'Send message', :id => "download-button", :class => "btn-large waves-effect waves-light orange" %>
	</div>
	
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grafficards</title>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag	 'application', "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css" %>
  <%= stylesheet_link_tag	 'application', "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  <%= stylesheet_link_tag	 'application', "https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" %>
  <%= stylesheet_link_tag	 'application', "https://fonts.googleapis.com/css?family=Dancing+Script:700" %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js" %>
  <%= csrf_meta_tags %>

</head>
<body>

<!-- ========================== NAVBAR STARTS HERE============================== -->

<div class="navbar-fixed">
  <nav class="light-blue lighten-1 z-depth-0" role="navigation">
    <div class="nav-wrapper container">
    <%= link_to 'Grafficards', root_path, class: 'brand-logo' %>
      <ul class="right hide-on-med-and-down">
        <li><a><%= link_to 'About', about_path %></a></li>
        <li><a><%= link_to 'Contact', contact_path %></a></li>
        <li><a><%= link_to 'Blog', blog_path %></a></li>
      <ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a><%= link_to 'About', about_path %></a></li>
        <li><a><%= link_to 'Contact', contact_path %></a></li>
        <li><a><%= link_to 'Blog', blog_path %></a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
</div>

<!-- ========================== NAVBAR ENDS HERE============================== -->

<%= yield %>

<!-- ========================== FOOTER STARTS HERE============================== -->

<footer class="page-footer orange">
    <div class="container">
          <ul class="contact-info container center">
            <li class="twitter"><a href="https://twitter.com/Grafficards"><i class="fa fa-twitter fa-2x menu-brown-text"></i></a></li>
            <li class="instagram"><a href="https://www.instagram.com/grafficards/"><i class="fa fa-instagram fa-2x menu-brown-text"></i></a></li>
            <li class="linkedin"><a href="https://www.linkedin.com/company/10373989?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A10373989%2Cidx%3A1-1-1%2CtarId%3A1473615626202%2Ctas%3Agrafficards"><i class="fa fa-linkedin-square fa-2x menu-brown-text"></i></a></li>
            <li class="angellist"><a href="https://angel.co/grafficards"><i class="fa fa-angellist fa-2x menu-brown-text"></i></a></li>
          </ul>
          <br>
      </div>
    </div>

    <div class="footer-copyright">
      <div class="left" id="copyright">
         &#169; 2015 Grafficards
      </div>
      <div class="container center">
      Made with <i class="fa fa-heart-o"></i> in Sofia
      </div>
    </div>
</footer>

<!-- ========================== FOOTER ENDS HERE============================== -->

</body>
</html>

app/views/pages/about.html.erb
<div class="container">
		<h2 class="header left orange-text light">About us</h2>
		<br>
		<br>
		<br>
		<br>
		<br>
		<p class="menu-brown-text flow-text">We're a small team of people who like what we do. And it shows. </p>

</div>

<div class="container">
		<h2 class="header left orange-text light">FAQ</h2>
		<br>
		<br>
		<br>
		<br>
		<br>
			<ul class="collapsible" data-collapsible="accordion">
			    <li>
			      <div class="collapsible-header menu-brown-text">1. How do I choose a postcard design?</div>
			      <div class="collapsible-body "><p>Go <%= link_to "here", gallery_path %> and follow the instructions.</p></div>
			    </li>
			    <li>
			      <div class="collapsible-header menu-brown-text">2. Are there any additional charges?</div>
			      <div class="collapsible-body"><p>No. You pay what you see in the final step of your purchase.</p></div>
			    </li>
			    <li>
			      <div class="collapsible-header menu-brown-text">3. Can I pay with a debit/credit card?</div>
			      <div class="collapsible-body"><p>For the time being we can only accept payments via PayPal. Sorry.</p></div>
			    </li>
			    <li>
			      <div class="collapsible-header menu-brown-text">4. How long until my postcard reaches its destination?</div>
			      <div class="collapsible-body"><p>Around 3-4 days for Europe.</p></div>
			    </li>
			    <li>
			      <div class="collapsible-header menu-brown-text">5. Oops! I gave a wrong address. How can I fix this?</div>
			      <div class="collapsible-body"><p> Drop us a line here. We'll fix things.</p></div>
			    </li>
		  	</ul>

</div>

<div class="container">
		<h2 class="header left orange-text light">Privacy policy</h2>
		<br>
		<br>
		<br>
		<br>
		<br>

					<ul class="collapsible" data-collapsible="accordion">
			    <li>
			      <div class="collapsible-header menu-brown-text">Content</div>
			      <div class="collapsible-body "><p>This privacy policy discloses the privacy practices for www.grafficards.com. This privacy policy applies solely to information collected by this web site. It will notify you of the following:<br>
			    <br>
				1. What personally identifiable information is collected from you through the web site, how it is used and with whom it may be shared.<br>
				2. What choices are available to you regarding the use of your data.<br>
				3. The security procedures in place to protect the misuse of your information.<br>
				4. How you can correct any inaccuracies in the information.</p></div>
			    </li>
			    <li>
			      <div class="collapsible-header menu-brown-text">Information Collection, Use, and Sharing</div>
			      <div class="collapsible-body"><p>We are the sole owners of the information collected on this site. We only have access to/collect information that you voluntarily give us via email or other direct contact from you. We will not sell or rent this information to anyone.

				We will use your information to respond to you, regarding the reason you contacted us. We will not share your information with any third party outside of our organization, other than as necessary to fulfill your request, e.g. to ship an order.

				Unless you ask us not to, we may contact you via email in the future to tell you about specials, new products or services, or changes to this privacy policy.</p></div>
			    </li>
			    <li>
			      <div class="collapsible-header menu-brown-text">Your Access to and Control Over Information</div>
			      <div class="collapsible-body"><p>You may opt out of any future contacts from us at any time. You can do the following at any time by contacting us via the email form given on our website:<br>
			      	<br>
				   • See what data we have about you, if any.<br>

				   • Change/correct any data we have about you.<br>

				   • Have us delete any data we have about you.<br>

				   • Express any concern you have about our use of your data.</p></div>
			    </li>
			    <li>
			      <div class="collapsible-header menu-brown-text">Security</div>
			      <div class="collapsible-body"><p>We take precautions to protect your information. When you submit sensitive information via the website, your information is protected both online and offline.

				Wherever we collect sensitive information (such as credit card data), that information is encrypted and transmitted to us in a secure way. You can verify this by looking for a closed lock icon at the bottom of your web browser, or looking for "https" at the beginning of the address of the web page.

				While we use encryption to protect sensitive information transmitted online, we also protect your information offline. Only employees who need the information to perform a specific job (for example, billing or customer service) are granted access to personally identifiable information. The computers/servers in which we store personally identifiable information are kept in a secure environment.</p></div>
			    </li>
			    <li>
			      <div class="collapsible-header menu-brown-text">Updates</div>
			      <div class="collapsible-body"><p>Our Privacy Policy may change from time to time and all updates will be posted on this page.<br>
			     <br>
				If you feel that we are not abiding by this privacy policy, you should contact us immediately via email from our contact form.</p></div>
			    </li>
		  	</ul>
		<br>
</div>

app/views/pages/blog.html.erb
<div class='container'>
<h1>Coming soon...</h1>
</div>

app/views/pages/gallery.html.erb
<br>
<div class="row center">
	<h4 class="header col s12 light">Choose one of our hand-drawn designs</h4>
</div>

	<div class="center">
		<div class="col s12 m6 l3 gallery_img">
			<%= image_tag ("/assets/test-1.jpg"), :class => "materialboxed", :width =>"250" %>
		</div>

		<div class="col s12 m6 l3 gallery_img">
			<%= image_tag ("/assets/test-1.jpg"), :class => "materialboxed", :width =>"250" %>
		</div>
		
		<div class="col s12 m6 l3 gallery_img">
			<%= image_tag ("/assets/test-1.jpg"), :class => "materialboxed", :width =>"250" %>
		</div>

		<div class="col s12 m6 l3 gallery_img">
			<%= image_tag ("/assets/test-1.jpg"), :class => "materialboxed", :width =>"250" %>
		</div>

		<div class="col s12 m6 l3 gallery_img">
			<%= image_tag ("/assets/test-1.jpg"), :class => "materialboxed", :width =>"250" %>
		</div>
		
		<div class="col s12 m6 l3 gallery_img">
			<%= image_tag ("/assets/test-1.jpg"), :class => "materialboxed", :width =>"250" %>
		</div>
	</div>

<div class="container">
	<div class="row center next_button">
		<%= link_to "Next".html_safe, message_input_path, :id => "download-button", :class => "btn-large waves-effect waves-light orange" %>
	</div>
</div>

app/views/pages/home.html.erb
<section class="intro">
  <div class="section no-pad-bot" id="index-banner">
      <div class="container">
        <br><br>
        <h1 class="header center orange-text">Let them know you care!</h1>
        
        <div class="row center">
          <h5 class="header col s12 light">A handcrafted beautiful postcard with your message inside</h5>
        </div>

        <div class="homepage_img center">
        <%= image_tag "12.png", :width =>"400" %>
        </div>

        <div class="row center">
          <%= link_to "Try it out".html_safe, gallery_path, :id => "download-button", :class => "btn-large waves-effect waves-light orange" %>
        </div>
        <br><br>

      </div>
  </div>
</section>

  <div class="row center">
      <h4 class="header col s12 light">Why send a Grafficard?</h4>
      <br><br><br><br>
    <ul class="container center" id="double">
      <li class="col s12 m6 l3 homepage_reasons"><%= image_tag "14.png", :width =>"270" %></li>

      <li class="col s12 m6 l3 homepage_reasons">
        <h5 class="header light left-align"><i class="fa fa-hashtag orange-text"></i> Super easy</h5>
      </li>

      <li class="col s12 m6 l3 homepage_reasons">
        <h5 class="header light left-align"><i class="fa fa-hashtag orange-text"></i> Hand-written message</h5>
      </li>

      <li class="col s12 m6 l3 homepage_reasons">
        <h5 class="header light left-align"><i class="fa fa-hashtag orange-text"></i> Beautiful design</h5>
      </li>

      <li class="col s12 m6 l3 homepage_reasons">
        <h5 class="header light left-align"><i class="fa fa-hashtag orange-text"></i> Sent from your name</h5>
      </li>
    </ul>
  </div>

<br><br><br>

  <div class="page-footer yellow lighten-5">
    <br>
    <div class="row center">
      <h4 class="header col s12 light">How it works</h4>
    </div>
      <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center menu-brown-text"><i class="fa fa-picture-o"></i></h2>
            <h5 class="center">Choose a design</h5>

            <p class="light">We put a lot of love and care into not just drawing postcards but also giving them character. Our designs are simple, clean and hand-drawn with pen and paper, just like in the old days. Take a look at our collection and choose the card you like.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center menu-brown-text"><i class="fa fa-pencil-square-o"></i></h2>
            <h5 class="center">Write your message</h5>

            <p class="light">Put your thinking cap on! Here is where you create a personal message that will trully touch the hearts of those your card will be sent to. We'll make sure your message is beautifully hand-written onto the postcard of your choice.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center menu-brown-text"><i class="fa fa-paper-plane-o"></i></h2>
            <h5 class="center">Give us the address</h5>

            <p class="light">The last thing you need to do is put in the address where you want your postcard to be sent to. We'll take care of the rest. The card of your choice, with your message, hand-written inside, will be sent to the address you put in.</p>
          </div>
        </div>
      </div>

    </div>

    <div class="section">

      <div class="row center">
        <%= link_to "Try it out".html_safe, gallery_path, :id => "download-button", :class => "btn-large waves-effect waves-light orange" %>
      </div> 
    </div>
  </div>
            <div class="section">
            </div> 
  </div>

    <div class="row center">
      <br>
      <h4 class="header col s12 light">How it looks like</h4>
    </div>
    <div class="row center">
        <%= link_to "Try it out".html_safe, gallery_path, :id => "download-button", :class => "btn-large waves-effect waves-light orange" %>
    </div>
    <br>

app/views/pages/message_input.html.erb
<br>
<div class="row center">
	<h4 class="header col s12 light">Write your message</h4>
</div>
	<br>

<div class="row">
	<form>
	  <div class="row">
	  	<div class="col s12 m4 l2"><p></p></div>
	    	<div class="input-field col s12 m4 l8">
		      	<i class="material-icons prefix">mode_edit</i>
		      	<textarea id="icon_prefix2" class="materialize-textarea"></textarea>
		      	<label for="icon_prefix2">Message</label>
		    </div>
	  </div>
	</form>
</div>

<div class="row">
	<form>
	  <div class="row">
	  <div class="col s12 m4 l8"><p></p></div>
	    <div class="input-field col s12 m2 l2">
	      <textarea id="textarea1" class="materialize-textarea"></textarea>
	      <label for="textarea1">Signed</label>
	    </div>
	  </div>
	</form>
</div>

<div class="container">
	<div class="row center next_button">
		<%= link_to "Next".html_safe, address_input_path, :id => "download-button", :class => "btn-large waves-effect waves-light orange" %>
	</div>
</div>